name: IT Onboarding
description: Get new hire setup with the IT basics.
title: "[Onboarding]: <employee-name>"
labels: ["access request", "onboarding"]
projects: ["DryRunSec/Main"]
assignees:
  - ccasey
  - cktricky
body:
  - type: markdown
    attributes:
      value: |
        ## Onboarding Request
        Please fill out the following information to get started with onboarding.
  - type: input
    id: contact
    attributes:
      label: Name of person being onboarded.
      placeholder: "ex: John Doe"
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Personal Email of person being onboarded.
      description: We will use this to send and invite to Google Workspace.
    validations:
      required: true
  - type: input
    id: manager
    attributes:
      label: Supervisor
      description: Supervisor or the person being onboarded. Approval comment to this issue will be needed before access is granted.
    validations:
      required: true
  - type: checkboxes
    id: access
    attributes:
      label: Access
      description: What access do you need? (Request anything else in the comments section or in a generic access request issue.)
      options:
        - label: Google Workspace
        - label: Slack
        - label: Notion
        - label: GitHub
  - type: input
    id: github-username
    attributes:
      label: Github Username
      description: If GitHub access is needed, please provide their GitHub username.
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Anything else we should know?
      render: shell

